[tox]
requires =
    tox-uv
envlist =
    lint
    django42
    django51
    django52
#    djangomain

[testenv]
runner = uv-venv-runner
commands = {envpython} -Wa -b -m coverage run -m django test --settings=tests.settings
deps =
    django42: Django~=4.2.0
    django51: Django~=5.1.0
    django52: Django~=5.2.0
#    djangomain: https://github.com/django/django/archive/main.tar.gz
    coverage[toml]

[testenv:lint]
basepython = python3
commands =
    black --target-version py312 --check --diff .
    ruff check .
    isort --check-only --diff .
    {envpython} -m django check --settings=tests.settings
    {envpython} -m django makemigrations --settings=tests.settings --no-input --dry-run --check
deps =
    black
    ruff
    isort>=5.0.2
    Django>=4.2
