# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_event_color_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'permissions': (('view_calendar', 'View Calendar'),), 'verbose_name': 'calendar', 'verbose_name_plural': 'calendar'},
        ),
        migrations.AlterModelOptions(
            name='calendarrelation',
            options={'permissions': (('view_calendar_relation', 'View Calendar Relation'),), 'verbose_name': 'calendar relation', 'verbose_name_plural': 'calendar relations'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('view_event', 'View Event'),), 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventrelation',
            options={'permissions': (('view_event_relation', 'View Event Relation'),), 'verbose_name': 'event relation', 'verbose_name_plural': 'event relations'},
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'permissions': (('view_occurrence', 'View Occurrence'),), 'verbose_name': 'occurrence', 'verbose_name_plural': 'occurrences'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'permissions': (('view_occurrence', 'View Occurrence'),), 'verbose_name': 'rule', 'verbose_name_plural': 'rules'},
        ),
    ]
