# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_text_fields_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'calendar', 'verbose_name_plural': 'calendars'},
        ),
    ]
