# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='desc'),
        ),
    ]
