# Generated by Django 4.0.6 on 2022-09-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0014_use_autofields_for_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The end time must be later than the start time.",
                null=True,
                verbose_name="end",
            ),
        ),
    ]
