# Generated by Django 5.2.11 on 2026-02-18 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0016_alter_rule_name_ruleparam_ruleparamvariant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updater",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updater",
            ),
        ),
    ]
