# Generated by Django 5.2.11 on 2026-02-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0017_event_updater_alter_event_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendar",
            options={
                "ordering": ["name"],
                "verbose_name": "calendar",
                "verbose_name_plural": "calendars",
            },
        ),
        migrations.AddField(
            model_name="calendar",
            name="color_event",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=10,
                verbose_name="Color event",
            ),
        ),
    ]
