# Generated by Django 5.2.11 on 2026-02-18 10:52

import django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0018_alter_calendar_options_calendar_color_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=models.CharField(
                default="UTC", max_length=40, verbose_name="time zone"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                **{
                    "condition" if django.VERSION >= (5, 0) else "check": models.Q(
                        ("end__gte", models.F("start"))
                    )
                },
                name="check_start_end_date_ordering",
            ),
        ),
    ]
