name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Python ${{ matrix.python-version }} / ${{ matrix.tox-environment }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"
        tox-environment:
          - django32
          - django40
          - django41
        include:
          - python-version: 3.7
            tox-environment: django32
        # include:
        #   - python-version: 3.8
        #     tox-environment: djangomain
        #   - python-version: 3.9
        #     tox-environment: djangomain

    env:
      TOXENV: ${{ matrix.tox-environment }}
      COVERALLS_FLAG_NAME: Python ${{ matrix.python-version }} / ${{ matrix.tox-environment }}
      COVERALLS_PARALLEL: true
      COVERALLS_SERVICE_NAME: github
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install coveralls tox

      - name: Run tests
        run: tox

      - name: Upload coverage data to coveralls.io
        run: coveralls

  coveralls:
    name: Indicate completion to coveralls.io
    runs-on: ubuntu-latest

    needs: test
    # Push coverage report even if test cases failed
    if: ${{ always() }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Install coveralls
        run: python -m pip install coveralls

      - name: Report coverage to coveralls.io
        run: coveralls --finish
